export const actionTypes = {
  GET_ALL: "GET_ALL",
  GET_SHIP: "GET_SHIP",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
  ADJUST_QTY: "ADJUST_QTY",
  ITEM_DETAILS: "ITEM_DETAILS",
  CLEANUP_ITEM: "CLEANUP_ITEM"
}